title: Man Yao | 姚曼
logo:  # you can add own logo.
description: Assistant Professor, Denison University
baseurl:
url: https://yaoman1324.github.io # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: Man Yao, PhD
  description: Assistant Professor, Denison University
  image: '/assets/img/yao_website_photo.jpg'
  job: 
  bio: |+
    <br />
    My name is Man Yao, and I usually go by Yao. I'm a quantitative sociologist and an assistant professor of Women's and Gender Studies at <a href="https://denison.edu/people/man-yao">Denison University</a>. I received my PhD degree from the <a href="https://sociology.osu.edu/">Department of Sociology</a> at <a href="https://www.osu.edu/">The Ohio State University</a>. You could find my updated CV <a href="https://yaoman1324.github.io/assets/files/Yao_CV.pdf">here</a>.
    <br />
    <br />
    My research examines how gender inequality persists in contemporary socieites, including the United States and China. I am particularly interested in examining how gender differences are constructed and perpetuate in the digital age, by combining computational techniques with traditional social science methods. <br />    
    <br />
    I grew up in a small city called <a href="https://en.wikipedia.org/wiki/Enshi_Tujia_and_Miao_Autonomous_Prefecture">Enshi</a> on the mountainous southwestern corner of Hubei province, China. Then, I lived in Beijing and received a M.A. in Anthropology and B.A. in Sociology, both from <a href="https://www.ruc.edu.cn/en">Renmin University of China</a>. During this period, I conducted ethnographic work in an elementary school for migrant children on the outskirts of Beijing for three years.
    <br />
    
  resume: https://yaoman1324.github.io/assets/files/Yao_CV.pdf
  email: many@denison.edu
  # github: https://github.com/sho-kawano
  google_scholar: https://scholar.google.com/citations?hl=en&user=kgGuaI4AAAAJ&view_op=list_works&authuser=1&sortby=pubdate
  last_update:  2025-06-30



# Contact links
# TODO: Potentially add later.
# contact:
#   - name: Twitter
#     link: https://twitter.com/
#

# Comment Section (Disqus)
disqus-identifier:  # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics: UA-208765987-1
# add your identifier. For example UA-99631805-1.


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
