title: Man Yao
logo:  # you can add own logo.
description: PhD Candidate in Sociology, The Ohio State University
baseurl:
url: https://yaoman1324.github.io # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: Man Yao, PhD Candidate
  description: PhD Candidate in Sociology, The Ohio State University
  image: '/assets/img/profile-3.jpg'
  job: 
  bio: |+
    <br />
    I'm Yao, and I’m a PhD candidate in the <a href="https://sociology.osu.edu/">Department of Sociology</a> at <a href="https://www.osu.edu/">The Ohio State University</a>. My research focuses on social stratification and inequality in contemporary U.S. and Chinese societies, with an emphasis on gender, race and ethnicity, and education. 
    <br />
    <br />
    I will join Denison University as an Assistant Professor of Women's and Gender Studies, starting in August 2024.
    <br />
    <br />
    You could find my updated CV <a href="https://yaoman1324.github.io/assets/files/Yao_CV.pdf">here</a>.
    <br />    
    <br />
    One thread of my work explores how cultural beliefs about group distinctions allow gender and racial inequalities to persist. A second thread of my research examines how social statuses—such as gender, race, socioeconomic status, and family structure—shape access and returns to education. Methodologically, I combine traditional social science methods (e.g., survey, experiment, and interview) with computational techniques and big data to analyze these topics.
    <br />
    <br />
    My dissertation examines gender perceptions about Chinese names written in English letters and its consequences in everyday life. This dissertation leverages a mixed-method approach that includes computational text analysis, an online experiment, and qualitative interviews.
    <br />
    <br />
    I grew up in a small city called <a href="https://en.wikipedia.org/wiki/Enshi_Tujia_and_Miao_Autonomous_Prefecture">Enshi</a> on the mountainous southwestern corner of Hubei province, China. Then, I lived in Beijing and received a M.A. in Anthropology and B.A. in Sociology, both from <a href="https://www.ruc.edu.cn/en">Renmin University of China</a>. During this period, I conducted ethnographic work in an elementary school for migrant children on the outskirts of Beijing for three years.
    <br />
    
  resume: https://yaoman1324.github.io/assets/files/Yao_CV.pdf
  email: yao.630@osu.edu
  # github: https://github.com/sho-kawano
  google_scholar: https://scholar.google.com/citations?user=kgGuaI4AAAAJ&hl=zh-CN&oi=ao
  last_update:  2023-03-13



# Contact links
# TODO: Potentially add later.
# contact:
#   - name: Twitter
#     link: https://twitter.com/
#

# Comment Section (Disqus)
disqus-identifier:  # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics: UA-208765987-1
# add your identifier. For example UA-99631805-1.


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
