title: Man Yao
logo:  # you can add own logo.
description: PhD Candidate in Sociology, The Ohio State University
baseurl:
url: https://yaoman1324.github.io # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: Man Yao (姚曼)
  description: PhD Candidate in Sociology, The Ohio State University
  image: '/assets/img/profile-3.jpg'
  job: Welcome to my page!
  bio: |+
    <br />
    I’m Yao, and I’m a PhD candidate in the department of sociology at The Ohio State University.

    I conduct research on the formation and persistency of status inequality (e.g., gender, race/ethnicity, and immigration status) in modern societies.
    I am particularly interested in how cultural beliefs about status groups are endorsed, diffused, and activated in interpersonal relationships to shape inequality.
    I leverage data from a variety of methodological approaches, including survey experiments, secondary large-scale survey analysis, and computational survey analysis.
    <br />
    
#   resume: 
#   email: shkawano@ucsc.edu
#   github: https://github.com/sho-kawano
#   linkedin: https://www.linkedin.com/in/shokawano
#   last_update:  2022-01-30



# Contact links
# TODO: Potentially add later.
# contact:
#   - name: Twitter
#     link: https://twitter.com/
#

# Comment Section (Disqus)
disqus-identifier:  # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics: UA-208765987-1
# add your identifier. For example UA-99631805-1.


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
